### PR TITLE
OpenDingux Beta: Prevent image cropping when using hardware/hardware_2x scalers with 'keep aspect ratio' enabled

### PR DESCRIPTION
**Pull request by jdgleaver**

### CODE REVIEW

**Comment by F2GD** [comment]
Is it possible to allow the menu binding to be changed in the config file? I want to remove the power button from triggering the menu, I use start + select instead. When waking from sleep in simple menu/Adam image it opens the reGBA menu

**Comment by jdgleaver** [comment]
@F2GD It should be possible to selectively disable the power button 'hotkey'. I'm a little busy right now, but I shall add it to the TODO list.

**Comment by F2GD** [comment]
> @F2GD It should be possible to selectively disable the power button 'hotkey'. I'm a little busy right now, but I shall add it to the TODO list.

That's awesome thanks man! No rush at all :)

**Comment by jdgleaver** [comment]
@F2GD This new release should do the trick: https://github.com/jdgleaver/ReGBA/releases/tag/1.9.2

**Pull request merged**
